env:
   - TERM=dumb

language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

before_install:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoTestReport coveralls

after_failure:
 - ./gradlew clean check --debug