env:
   - TERM=dumb

language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:
 - chmod +x gradlew
 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/80dd1065215c5b6e25af
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
